import type { EpochMs, EventId, TrustLayer, Unit } from '@scora/trust-core';

/**
 * Layer 09 — the AI interview.
 *
 * The strongest available evidence of ownership is a developer explaining their
 * own work. This layer generates questions **from the session** — from the code
 * that was written, the bug that was fixed, the completion that was accepted —
 * and grades the answers on whether they match what actually happened.
 *
 * Two rules shape everything below.
 *
 * **A question that could be asked of anyone proves nothing.** Generic trivia
 * measures interview practice and English fluency. Every `InterviewQuestion`
 * therefore carries `groundedIn` — the event ids it was built from — and the
 * planner cannot emit a question with an empty grounding. That is why the
 * question bank is derived rather than authored.
 *
 * **A wrong answer is not a dishonest answer.** People forget what they wrote
 * an hour ago, explain badly under pressure, and interview poorly in a second
 * language. The grade that matters for trust is `consistencyWithCode` — does the
 * explanation match the artefact? — and even that is reported with a confidence
 * and a `NOT_ANSWERED` outcome that carries no penalty, exactly as Layer 08
 * treats an unexercised skill.
 *
 * The examiner is a **port**, not an implementation. The model that writes
 * questions and grades answers is configured by the tenant administrator; this
 * package defines the interface it must satisfy and never reaches for a network.
 */

export const QuestionTopic = {
  IMPLEMENTATION_CHOICE: 'implementation_choice',
  LIBRARY_CHOICE: 'library_choice',
  BUG_CAUSE: 'bug_cause',
  REQUIREMENT_CHANGE: 'requirement_change',
  FUNCTION_EXPLANATION: 'function_explanation',
  ALTERNATIVE_APPROACHES: 'alternative_approaches',
  ARCHITECTURE: 'architecture',
  AI_ASSISTED_REGION: 'ai_assisted_region',
} as const;

export type QuestionTopic = (typeof QuestionTopic)[keyof typeof QuestionTopic];

export const Difficulty = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
  EXPERT: 'expert',
} as const;

export type Difficulty = (typeof Difficulty)[keyof typeof Difficulty];

export const DIFFICULTY_ORDER: readonly Difficulty[] = [
  Difficulty.EASY,
  Difficulty.MEDIUM,
  Difficulty.HARD,
  Difficulty.EXPERT,
];

export function difficultyOrdinal(difficulty: Difficulty): number {
  return DIFFICULTY_ORDER.indexOf(difficulty);
}

/**
 * A question the session earned.
 *
 * `groundedIn` is not metadata. It is the reason the question is admissible: it
 * points at the events the question was derived from, so a developer who
 * disputes a question can be shown exactly what prompted it, and so a question
 * with no basis in the session cannot be constructed at all.
 */
export interface InterviewQuestion {
  readonly questionId: string;
  readonly topic: QuestionTopic;
  readonly difficulty: Difficulty;
  /** The events this question was built from. Never empty. */
  readonly groundedIn: readonly EventId[];
  /**
   * What the developer is being asked about, in the engine's own words.
   *
   * The examiner turns this into the phrasing the developer sees. Keeping the
   * subject separate from the wording means the grounding survives even when the
   * question text is generated by a model the engine does not control.
   */
  readonly subject: string;
  /** Layer the grounding came from, for corroboration accounting. */
  readonly sourceLayer: TrustLayer;
  /**
   * What a sound answer must account for.
   *
   * Facts the session already established — the error class that was fixed, the
   * dependency that was added. The grader checks the answer against these rather
   * than against a model's opinion of a good answer.
   */
  readonly expectedPoints: readonly string[];
  /** Skill this question also tests, when it was generated from a claim. */
  readonly skillId: string | null;
}

export const AnswerOutcome = {
  /** Explanation matched the artefact. */
  CONSISTENT: 'CONSISTENT',
  /** Broadly right, thin on specifics. Ordinary for work done an hour ago. */
  PARTIAL: 'PARTIAL',
  /** Fluent, plausible, and describes code other than the code they wrote. */
  INCONSISTENT: 'INCONSISTENT',
  /** No answer, or an answer too short to grade. Carries no penalty. */
  NOT_ANSWERED: 'NOT_ANSWERED',
  /** The grader itself was not confident enough to be used. */
  UNGRADED: 'UNGRADED',
} as const;

export type AnswerOutcome = (typeof AnswerOutcome)[keyof typeof AnswerOutcome];

/**
 * A graded answer, after the engine has applied its own floors.
 *
 * Four separate scores rather than one, because they fail independently and
 * conflating them is how a nervous developer gets scored as a dishonest one.
 * `consistencyWithCode` is the only one that speaks to ownership: an answer can
 * be shallow and correct, or fluent and wrong about their own code, and those
 * mean opposite things.
 */
export interface AnswerGrade {
  readonly questionId: string;
  readonly outcome: AnswerOutcome;
  /** Is the answer technically right? */
  readonly correctness: Unit;
  /** How far past the surface does it go? */
  readonly depth: Unit;
  /** Does it cite specifics from their own work, or could it describe any codebase? */
  readonly specificity: Unit;
  /** Does the explanation match what the session shows they actually did? */
  readonly consistencyWithCode: Unit;
  /** The grader's own confidence. Below the floor, the grade is not used at all. */
  readonly graderConfidence: Unit;
  /** Identifier of the grading model, recorded so a grade can be re-examined later. */
  readonly graderModel: string;
  /** Plain-language justification, shown to reviewer and developer alike. */
  readonly rationale: string;
}

/**
 * What a tenant-configured examiner returns: plain numbers, no verdict.
 *
 * Deliberately *not* an `AnswerGrade`. Two things follow from that.
 *
 * The scores are ordinary `number`s rather than branded `Unit`s, so a provider
 * cannot assert a value into range — it reports what it thinks, and
 * `normaliseGrade` is the only thing that can produce a `Unit`. A grader that
 * returns 1.7 confidence gets clamped instead of smuggling an impossible value
 * through the engine.
 *
 * And there is no `outcome`. The engine decides whether an answer was consistent,
 * from the scores and its own thresholds. A provider that could name the outcome
 * directly would be deciding trust, which is not what it was configured to do.
 */
export interface RawGrade {
  readonly questionId: string;
  readonly correctness: number;
  readonly depth: number;
  readonly specificity: number;
  readonly consistencyWithCode: number;
  readonly graderConfidence: number;
  readonly graderModel: string;
  readonly rationale: string;
}

export interface InterviewAnswer {
  readonly questionId: string;
  readonly responseMs: number;
  readonly wordCount: number;
  /** Reference into secure storage. The transcript itself never enters this package. */
  readonly transcriptRef: string | null;
}

export interface InterviewExchange {
  readonly question: InterviewQuestion;
  readonly answer: InterviewAnswer | null;
  readonly grade: AnswerGrade | null;
}

export const InterviewVerdict = {
  /** Explained their work consistently. The strongest positive signal available. */
  DEMONSTRATES_OWNERSHIP: 'DEMONSTRATES_OWNERSHIP',
  /** Explained some of it. Common, and not adverse. */
  PARTIAL_OWNERSHIP: 'PARTIAL_OWNERSHIP',
  /** Explanations conflicted with the artefact across several questions. */
  EXPLANATION_INCONSISTENT: 'EXPLANATION_INCONSISTENT',
  /** Too few graded answers to say anything. */
  INCONCLUSIVE: 'INCONCLUSIVE',
  /** No interview took place. Distinct from a failed one. */
  NOT_CONDUCTED: 'NOT_CONDUCTED',
} as const;

export type InterviewVerdict = (typeof InterviewVerdict)[keyof typeof InterviewVerdict];

export interface InterviewResult {
  readonly interviewId: string;
  readonly assessedAt: EpochMs;
  readonly verdict: InterviewVerdict;
  readonly exchanges: readonly InterviewExchange[];
  /** Mean consistency across graded answers, or null when nothing was gradeable. */
  readonly ownership: Unit | null;
  readonly confidence: Unit;
  /** Topics the interview never reached. Coverage, in Layer 08's sense. */
  readonly notCovered: readonly QuestionTopic[];
  readonly limitations: readonly string[];
  readonly summary: string;
  readonly policyVersion: string;
}

/**
 * The examiner port.
 *
 * Everything model-shaped lives behind this interface: phrasing a grounded
 * subject as a question, and grading an answer against the points the session
 * established. The engine supplies the grounding and enforces the rules; the
 * provider supplies language.
 *
 * Two things it is deliberately not given: the developer's identity, and the
 * Trust score so far. A grader that knows the session is already suspected will
 * find reasons to agree.
 */
export interface Examiner {
  /** Renders a grounded subject into the wording the developer will see. */
  phrase(question: InterviewQuestion): Promise<string>;
  /**
   * Grades an answer against `expectedPoints`, returning raw scores.
   * May decline by returning low confidence — the engine will discard the grade.
   */
  grade(request: GradingRequest): Promise<RawGrade>;
}

export interface GradingRequest {
  readonly question: InterviewQuestion;
  readonly answerText: string;
  readonly responseMs: number;
}

/**
 * An examiner that grades nothing.
 *
 * The default. A tenant that has configured no provider gets an interview layer
 * that returns `NOT_CONDUCTED` — not an interview that quietly grades on
 * heuristics.
 */
export const NO_EXAMINER: Examiner = {
  async phrase(question) {
    return question.subject;
  },
  async grade(request) {
    return {
      questionId: request.question.questionId,
      correctness: 0,
      depth: 0,
      specificity: 0,
      consistencyWithCode: 0,
      graderConfidence: 0,
      graderModel: 'none',
      rationale: 'No examiner is configured for this tenant, so no answer was graded.',
    };
  },
};
