import { notFound } from "next/navigation";
import { query, queryOne } from "@/lib/db";
import { AdmissionDecisionForm } from "@/components/admission-decision-form";

const eventLabels:Record<string,string>={ASSESSMENT_STARTED:"بدأ المطور الاختبار",ASSESSMENT_SUBMITTED:"سلّم المطور الاختبار",INTERVIEW_ANSWER_RECEIVED:"تم استلام إجابة مقالية",INTERVIEW_ANSWER_SCORED:"قيّم AI الإجابة المقالية",REVIEW_DECISION_RECORDED:"سجل الأدمن قرار المراجعة",RESULT_RELEASED:"تم إرسال النتيجة للمطور"};
const sourceLabels:Record<string,string>={SERVER:"النظام",AI_SERVICE:"الذكاء الاصطناعي",SANDBOX:"بيئة الكود",HUMAN:"الأدمن"};

export default async function Page({params}:{params:Promise<{id:string}>}){
  const{id}=await params;
  const session=await queryOne<{id:number;public_id:string;status:string;model:string|null;display_name:string;email:string;username:string|null}>(`SELECT das.id,das.public_id,das.status,das.model,d.display_name,u.email,u.username FROM developer_assessment_sessions das JOIN developers d ON d.id=das.developer_id JOIN users u ON u.id=d.user_id WHERE das.public_id=?`,[id]);
  if(!session)notFound();
  const questions=await query<{id:number;kind:string;skill:string;question_text:string;answer_text:string|null;score:number|null;feedback:string|null;max_score:number}>(`SELECT q.id,q.kind,q.skill,q.question_text,q.max_score,a.answer_text,a.score,a.feedback FROM developer_assessment_questions q LEFT JOIN developer_assessment_answers a ON a.question_id=q.id WHERE q.session_id=? ORDER BY q.position`,[session.id]);
  const events=await query<{event_type:string;source:string;created_at:Date;event_hash:string}>("SELECT event_type,source,created_at,event_hash FROM trust_events WHERE session_public_id=? ORDER BY chain_position",[id]);
  const interviews=await query<{public_id:string;question_text:string;response_transcript:string|null;audio_url:string|null;asked_at:Date;answered_at:Date|null}>("SELECT public_id,question_text,response_transcript,audio_url,asked_at,answered_at FROM developer_interview_rounds WHERE session_id=? ORDER BY position",[session.id]);
  const maximum=questions.reduce((sum,q)=>sum+q.max_score,0),earned=questions.reduce((sum,q)=>sum+(q.score??0),0),percent=maximum?Math.round(earned/maximum*100):0;
  const suggestedTrust=Math.max(0,Math.min(90,percent)),suggestedSp=Math.max(0,percent*10);
  return <main dir="rtl" className="mx-auto max-w-5xl space-y-6 px-6 py-10"><div><a href="/admin" className="text-[#056B38]">← لوحة الإدارة</a><h1 className="mt-3 text-3xl font-extrabold">مراجعة {session.display_name}</h1><p className="text-gray-600">@{session.username} · {session.email} · النموذج: {session.model||"غير مسجل"}</p></div>
    <section className="grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-6 md:grid-cols-3"><div><div className="text-sm text-gray-600">نتيجة تقييم AI</div><div className="text-3xl font-extrabold text-[#056B38]">{percent}%</div></div><div><div className="text-sm text-gray-600">Trust المقترح</div><div className="text-2xl font-extrabold">{suggestedTrust}</div></div><div><div className="text-sm text-gray-600">SP المقترح</div><div className="text-2xl font-extrabold">{suggestedSp}</div></div><p className="text-xs text-gray-600 md:col-span-3">هذه توصية مبنية على درجات الإجابات. القرار والقيم النهائية يحددها الأدمن.</p></section>
    {questions.map((q,i)=><article key={q.id} className="rounded-2xl border bg-white p-6"><div className="text-xs font-bold text-[#056B38]">{q.kind==="code"?"كود Sandbox":q.kind==="mcq"?"اختيار من متعدد":"سؤال مقالي"} · {q.skill}</div><h2 className="mt-2 font-extrabold">{i+1}. {q.question_text}</h2><pre className={`mt-4 overflow-x-auto whitespace-pre-wrap rounded-xl p-4 ${q.kind==="code"?"bg-[#0f172a] text-[#d1fae5]":"bg-gray-50"}`}>{q.answer_text||"لم تتم الإجابة"}</pre>{q.score!==null&&<p className="mt-3 font-bold">الدرجة: {q.score} / {q.max_score}</p>}{q.feedback&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">ملاحظة AI: {q.feedback}</p>}</article>)}
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-extrabold">المقابلة الصوتية ({interviews.length} جولات)</h2><div className="mt-4 space-y-4">{interviews.length?interviews.map((round,i)=><article key={round.public_id} className="rounded-xl border p-4"><div className="font-bold">سؤال {i+1}: {round.question_text}</div><p className="mt-3 whitespace-pre-wrap rounded-lg bg-gray-50 p-3">{round.response_transcript||"لم يتم تسجيل إجابة"}</p>{round.audio_url&&<audio controls preload="metadata" className="mt-3 w-full" src={round.audio_url}/>}</article>):<p className="text-gray-500">لا توجد جولات مقابلة محفوظة.</p>}</div></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-extrabold">سجل Trust Engine المترجم ({events.length})</h2><div className="mt-4 space-y-2">{events.map((event,i)=><div key={i} className="rounded-xl bg-gray-50 p-3 text-sm"><b>{eventLabels[event.event_type]||event.event_type}</b> · {sourceLabels[event.source]||event.source}<div className="mt-1 text-xs text-gray-500">{new Date(event.created_at).toLocaleString("ar-EG")}</div><div className="truncate font-mono text-[10px] text-gray-400">{event.event_hash}</div></div>)}</div></section>
    {session.status==="admin_review"&&<AdmissionDecisionForm assessmentPublicId={session.public_id}/>}</main>;
}
