"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import dynamic from "next/dynamic";
import { loader } from "@monaco-editor/react";
import { Code2,Mic,MicOff,Send } from "lucide-react";

loader.config({paths:{vs:"/monaco/vs"}});
const MonacoEditor=dynamic(()=>import("@monaco-editor/react"),{ssr:false,loading:()=> <div className="flex h-[420px] items-center justify-center bg-[#0f172a] text-gray-400">جارٍ تشغيل محرر الكود...</div>});
type Question={publicId:string;kind:string;skill:string;text:string;options:string[]|null};
type Round={public_id:string;question_text:string;response_transcript:string|null;audio_url:string|null};
type SpeechRecognitionLike={lang:string;interimResults:boolean;continuous:boolean;start():void;stop():void;onresult:((event:{results:ArrayLike<{0:{transcript:string};isFinal:boolean}>})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null};

function language(skill:string){const v=skill.toLowerCase();if(v.includes("python"))return"python";if(v.includes("typescript"))return"typescript";if(v.includes("javascript")||v.includes("node"))return"javascript";if(v.includes("c++"))return"cpp";if(v.includes("c#"))return"csharp";if(v.includes("java"))return"java";if(v.includes("php"))return"php";if(v.includes("sql"))return"sql";if(v.includes("html"))return"html";if(v.includes("css"))return"css";if(v.includes("go"))return"go";if(v.includes("rust"))return"rust";return"plaintext"}
function clock(seconds:number){const safe=Math.max(0,seconds),m=Math.floor(safe/60),s=safe%60;return`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}

export function DeveloperAssessmentForm({publicId,questions,initialAnswers,initialRemaining}:{publicId:string;questions:Question[];initialAnswers:Record<string,string>;initialRemaining:number}){
  const ordered=useMemo(()=>[...questions].sort((a,b)=>Number(b.kind==="code")-Number(a.kind==="code")),[questions]);
  const [answers,setAnswers]=useState(initialAnswers),[index,setIndex]=useState(0),[remaining,setRemaining]=useState(initialRemaining),[phase,setPhase]=useState<"assessment"|"interview"|"complete">("assessment"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(true),[rounds,setRounds]=useState<Round[]>([]),[recording,setRecording]=useState(false),[transcript,setTranscript]=useState("");
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),recognition=useRef<SpeechRecognitionLike|null>(null),latestAudio=useRef<Blob|null>(null);
  const current=ordered[index];
  const save=useCallback(async(payload=answers)=>{if(phase!=="assessment")return;setSaved(false);const response=await fetch(`/api/developer-assessment/${publicId}/state`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentQuestionId:current?.publicId??null,answers:Object.fromEntries(Object.entries(payload).map(([id,value])=>{const q=ordered.find(item=>item.publicId===id);return[id,{value,type:q?.kind==="code"?"code":q?.kind==="mcq"?"mcq":"text",clientState:{questionIndex:index}}]}))})});const data=await response.json();if(data.expired){setRemaining(0);setPhase("complete")}else if(response.ok){setRemaining(data.remainingSeconds);setSaved(true)}},[answers,current?.publicId,index,ordered,phase,publicId]);
  useEffect(()=>{const timer=setTimeout(()=>{void save()},700);return()=>clearTimeout(timer)},[answers,index,save]);
  useEffect(()=>{const timer=setInterval(()=>setRemaining(value=>{if(value<=1){if(phase==="assessment")void save();else if(phase==="interview")void fetch(`/api/developer-assessment/${publicId}/interview`,{method:"POST",body:new FormData()});queueMicrotask(()=>setPhase("complete"));return 0}return value-1}),1000);return()=>clearInterval(timer)},[phase,publicId,save]);
  const setAnswer=(value:string)=>{if(!current||remaining<=0)return;setSaved(false);setAnswers(state=>({...state,[current.publicId]:value}))};

  async function beginInterview(){await save();setBusy(true);setError("");const response=await fetch(`/api/developer-assessment/${publicId}/interview`,{method:"POST",body:new FormData()});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"تعذر بدء المقابلة");return}if(data.complete){setPhase("complete");return}setRounds([data.round]);setRemaining(data.remainingSeconds);setPhase("interview")}
  async function startVoice(){setError("");const SpeechCtor=(window as unknown as {SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).webkitSpeechRecognition;if(!SpeechCtor){setError("المتصفح لا يدعم تحويل الصوت إلى نص. استخدم Chrome أو Edge محدثًا.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];latestAudio.current=null;const media=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm"});recorder.current=media;media.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};media.onstop=()=>{latestAudio.current=new Blob(chunks.current,{type:media.mimeType});stream.getTracks().forEach(track=>track.stop())};const speech=new SpeechCtor();recognition.current=speech;speech.lang="ar-EG";speech.continuous=true;speech.interimResults=true;let finalText="";speech.onresult=event=>{let interim="";for(let i=0;i<event.results.length;i++){const result=event.results[i],text=result[0].transcript;if(result.isFinal)finalText+=`${text} `;else interim+=text}setTranscript(`${finalText}${interim}`.trim())};speech.onerror=e=>setError(`تعذر التعرف على الصوت: ${e.error}`);media.start(500);speech.start();setRecording(true)}catch{setError("تعذر الوصول للميكروفون. اسمح للموقع باستخدامه ثم حاول مرة أخرى.")}}
  function stopVoice(){recognition.current?.stop();recorder.current?.stop();setRecording(false)}
  function dictateWritten(){if(!current||current.kind==="mcq"||current.kind==="code")return;const SpeechCtor=(window as unknown as {SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).webkitSpeechRecognition;if(!SpeechCtor){setError("المتصفح لا يدعم الإملاء الصوتي. استخدم Chrome أو Edge محدثًا.");return}const speech=new SpeechCtor();speech.lang="ar-EG";speech.continuous=false;speech.interimResults=true;const original=answers[current.publicId]||"";speech.onresult=event=>{let text="";for(let i=0;i<event.results.length;i++)text+=`${event.results[i][0].transcript} `;setAnswer(`${original}${original?" ":""}${text.trim()}`)};speech.onerror=e=>setError(`تعذر التعرف على الصوت: ${e.error}`);speech.start()}
  async function sendVoice(){const round=rounds.at(-1);if(!round||!transcript.trim()||!latestAudio.current){setError("سجل إجابة صوتية كاملة أولًا");return}setBusy(true);setError("");const form=new FormData();form.set("roundId",round.public_id);form.set("transcript",transcript.trim());form.set("audio",latestAudio.current,"answer.webm");const response=await fetch(`/api/developer-assessment/${publicId}/interview`,{method:"POST",body:form}),data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"تعذر حفظ الإجابة الصوتية");return}setRounds(state=>state.map(item=>item.public_id===round.public_id?{...item,response_transcript:transcript}:item).concat(data.round?[data.round]:[]));setTranscript("");latestAudio.current=null;if(data.complete)setPhase("complete");else setRemaining(data.remainingSeconds)}
  async function finishAssessment(){const missing=ordered.some(q=>!String(answers[q.publicId]||"").trim());if(missing){setError("أجب عن كل أسئلة الاختبار قبل بدء المقابلة");return}await beginInterview()}

  if(phase==="complete")return <section className="rounded-2xl border bg-white p-10 text-center"><h2 className="text-2xl font-extrabold">انتهت الجلسة</h2><p className="mt-2 text-gray-600">تم حفظ آخر حالة وإرسالها لمراجعة الأدمن.</p></section>;
  return <div className="space-y-5"><div className="sticky top-3 z-20 flex items-center justify-between rounded-xl border bg-white/95 p-4 shadow-sm backdrop-blur"><div className="font-bold">{phase==="assessment"?`السؤال ${index+1} من ${ordered.length}`:`المقابلة الصوتية · الجولة ${rounds.length}`}</div><div className={`font-mono text-xl font-extrabold ${remaining<120?"text-red-600":"text-[#056B38]"}`}>{clock(remaining)}</div><div className="text-xs text-gray-500">{saved?"تم الحفظ":"جارٍ الحفظ..."}</div></div>
    {phase==="assessment"&&current&&<section className="rounded-2xl border bg-white p-6"><div className="text-xs font-bold text-[#056B38]">{current.kind==="code"?"مهمة برمجية":current.kind==="mcq"?"اختيار من متعدد":"سؤال كتابي"} · {current.skill}</div><h2 className="mt-3 whitespace-pre-wrap text-lg font-extrabold leading-8">{current.text}</h2>{current.kind==="code"?<div className="mt-5 overflow-hidden rounded-xl border bg-[#0f172a]" dir="ltr"><div className="flex items-center gap-2 border-b border-white/10 px-4 py-3 text-sm text-white"><Code2 className="h-4 w-4"/> solution · {language(current.skill)}</div><MonacoEditor path={`assessment://${publicId}/${current.publicId}`} height="480px" theme="vs-dark" language={language(current.skill)} value={answers[current.publicId]||""} onChange={value=>setAnswer(value||"")} options={{automaticLayout:true,fontSize:14,minimap:{enabled:true},wordWrap:"on",suggestOnTriggerCharacters:true,quickSuggestions:true,formatOnPaste:true,formatOnType:true,scrollBeyondLastLine:false,padding:{top:16,bottom:16}}}/></div>:current.options?<div className="mt-5 grid gap-3">{current.options.map(option=><label key={option} className={`flex cursor-pointer gap-3 rounded-xl border p-4 ${answers[current.publicId]===option?"border-[#056B38] bg-[#E8FAF0]":""}`}><input type="radio" checked={answers[current.publicId]===option} onChange={()=>setAnswer(option)}/><span>{option}</span></label>)}</div>:<div className="mt-5"><textarea value={answers[current.publicId]||""} onChange={e=>setAnswer(e.target.value)} className="min-h-48 w-full rounded-xl border p-4" placeholder="اكتب إجابتك هنا أو استخدم الإملاء الصوتي..."/><button type="button" onClick={dictateWritten} className="mt-3 flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-bold"><Mic className="h-4 w-4"/> إجابة باستخدام Live Voice</button></div>}<div className="mt-6 flex justify-between"><button type="button" disabled={index===0} onClick={()=>setIndex(i=>i-1)} className="rounded-lg border px-5 py-2 disabled:opacity-40">السابق</button>{index<ordered.length-1?<button type="button" onClick={()=>setIndex(i=>i+1)} className="rounded-lg bg-[#056B38] px-5 py-2 font-bold text-white">التالي</button>:<button type="button" disabled={busy} onClick={finishAssessment} className="rounded-lg bg-[#056B38] px-5 py-2 font-bold text-white">{busy?"جارٍ بدء المقابلة...":"بدء المقابلة الصوتية"}</button>}</div></section>}
    {phase==="interview"&&<section className="rounded-2xl border bg-white p-7"><div className="text-xs font-bold text-[#056B38]">AI Interview</div><h2 className="mt-3 text-xl font-extrabold leading-9">{rounds.at(-1)?.question_text}</h2><div className="mt-6 rounded-xl bg-gray-50 p-4 min-h-24">{transcript||"سيظهر نص إجابتك الصوتية هنا أثناء الحديث..."}</div><div className="mt-5 flex flex-wrap gap-3">{!recording?<button type="button" onClick={startVoice} className="flex items-center gap-2 rounded-full bg-red-600 px-6 py-3 font-bold text-white"><Mic className="h-5 w-5"/> بدء الإجابة الصوتية</button>:<button type="button" onClick={stopVoice} className="flex items-center gap-2 rounded-full bg-gray-900 px-6 py-3 font-bold text-white"><MicOff className="h-5 w-5"/> إيقاف التسجيل</button>}<button type="button" disabled={busy||recording||!transcript.trim()} onClick={sendVoice} className="flex items-center gap-2 rounded-full bg-[#056B38] px-6 py-3 font-bold text-white disabled:opacity-40"><Send className="h-4 w-4"/>{busy?"جارٍ تحليل الإجابة...":"إرسال الإجابة للـ AI"}</button></div></section>}
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}</div>;
}
