import "server-only";
import { createCipheriv,createDecipheriv,createHash,randomBytes } from "node:crypto";
import { z } from "zod";
import { query } from "@/lib/db";

const Question=z.object({kind:z.enum(["mcq","interview","code"]),skill:z.string().min(1).max(100),question:z.string().min(10),options:z.array(z.string()).min(2).max(6).optional(),expectedAnswer:z.unknown().optional(),maxScore:z.number().int().min(1).max(100)});
const Assessment=z.object({questions:z.array(Question).min(5).max(15)});
const GroupedQuestion=z.object({question:z.string().min(10),options:z.array(z.string()).min(2).max(6).optional(),expectedAnswer:z.unknown().optional(),maxScore:z.number().int().min(1).max(100).optional(),skill:z.string().min(1).max(100).optional()});
const GroupedAssessment=z.object({mcq:z.array(GroupedQuestion),interview:z.array(GroupedQuestion),code:z.union([GroupedQuestion,z.array(GroupedQuestion)])});
type GroupedQuestionValue=z.infer<typeof GroupedQuestion>;
const Grade=z.object({score:z.number().int().min(0),feedback:z.string().min(1).max(2000),correctness:z.number().min(0).max(1),depth:z.number().min(0).max(1),specificity:z.number().min(0).max(1),consistency:z.number().min(0).max(1),confidence:z.number().min(0).max(1)});
const InterviewTurn=z.object({question:z.string().min(10).max(2000),shouldContinue:z.boolean()});
function key(){const secret=process.env.SESSION_SECRET;if(!secret)throw new Error("SESSION_SECRET_REQUIRED");return createHash("sha256").update(secret).digest()}
export function encryptSecret(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv);const data=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `v1.${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${data.toString("base64url")}`}
function decryptSecret(value:string){const [,iv,tag,data]=value.split(".");const d=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));d.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([d.update(Buffer.from(data,"base64url")),d.final()]).toString("utf8")}
export async function openRouterConfig(){const rows=await query<{setting_key:string;setting_value:string}>("SELECT setting_key,setting_value FROM platform_settings WHERE setting_key IN ('openrouter_api_key','openrouter_model','openrouter_site_url','openrouter_site_title')");const m=Object.fromEntries(rows.map(x=>[x.setting_key,x.setting_value]));const stored=m.openrouter_api_key;return{apiKey:stored?decryptSecret(stored):process.env.OPENROUTER_API_KEY,model:m.openrouter_model||"openai/gpt-4.1-mini",siteUrl:m.openrouter_site_url||"http://localhost:3000",siteTitle:m.openrouter_site_title||"SCORA",hasStoredKey:Boolean(stored)}}
function parseModelJson(content:string){const clean=content.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(clean)}catch{const start=clean.indexOf("{"),end=clean.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(clean.slice(start,end+1));throw new Error("OPENROUTER_INVALID_JSON")}}
function normalizeAssessment(value:unknown,skills:string[]){
  const fallbackSkill=skills.join(", ");
  const normalize=(q:GroupedQuestionValue,kind:"mcq"|"interview"|"code")=>({
    ...q,
    kind,
    skill:q.skill||fallbackSkill,
    expectedAnswer:q.expectedAnswer??(kind==="mcq"?q.options?.[0]??"راجع الإجابة تقنيًا":"قيّم الإجابة وفق الدقة والعمق التقني"),
    maxScore:q.maxScore??(kind==="code"?40:kind==="interview"?20:10),
  });
  const direct=Assessment.safeParse(value);
  if(direct.success)return Assessment.parse({questions:direct.data.questions.map(q=>normalize(q,q.kind)).sort((a,b)=>Number(b.kind==="code")-Number(a.kind==="code"))});
  const grouped=GroupedAssessment.parse(value),code=Array.isArray(grouped.code)?grouped.code:[grouped.code];
  return Assessment.parse({questions:[...code.map(q=>normalize(q,"code")),...grouped.mcq.map(q=>normalize(q,"mcq")),...grouped.interview.map(q=>normalize(q,"interview"))]});
}
export async function generateAssessment(skills:string[],variationSeed=randomBytes(12).toString("hex"),previousQuestions:string[]=[]){const c=await openRouterConfig();if(!c.apiKey)throw new Error("OPENROUTER_NOT_CONFIGURED");const exclusions=previousQuestions.length?`Forbidden previous questions and close paraphrases: ${JSON.stringify(previousQuestions)}`:"No previous questions exist.";const prompt=`Create a unique Arabic developer admission assessment grounded only in these claimed skills: ${skills.join(", ")}. Variation seed: ${variationSeed}. ${exclusions} Create a realistic task with a new domain, constraints and edge cases. Return JSON with exactly 1 code question first, then 3 mcq questions related to reasoning about the coding task and 2 written questions. MCQ must include options. Include expectedAnswer and maxScore. Do not include markdown.`;let lastError:unknown;for(let attempt=0;attempt<2;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),150000);try{const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${c.apiKey}`,"HTTP-Referer":c.siteUrl,"X-OpenRouter-Title":c.siteTitle,"Content-Type":"application/json"},body:JSON.stringify({model:c.model,messages:[{role:"system",content:"You are SCORA's adaptive technical examiner. Output valid JSON only. Never repeat excluded questions or semantic equivalents."},{role:"user",content:prompt}],response_format:{type:"json_object"},reasoning:{exclude:true},max_tokens:6000,temperature:1}),signal:controller.signal,cache:"no-store"});if(!r.ok){lastError=new Error(`OPENROUTER_${r.status}`);if(r.status<500)throw lastError;continue}const raw=await r.json();const content=raw?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("OPENROUTER_INVALID_RESPONSE");return{assessment:normalizeAssessment(parseModelJson(content),skills),model:c.model,prompt,raw}}catch(error){lastError=error;if(!(error instanceof DOMException&&error.name==="AbortError"))throw error}finally{clearTimeout(timer)}}throw lastError instanceof Error?lastError:new Error("OPENROUTER_TIMEOUT")}

async function completeJson<T>(schema:z.ZodType<T>,system:string,prompt:string){const c=await openRouterConfig();if(!c.apiKey)throw new Error("OPENROUTER_NOT_CONFIGURED");let lastError:unknown;for(let attempt=0;attempt<2;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),120000);try{const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${c.apiKey}`,"HTTP-Referer":c.siteUrl,"X-OpenRouter-Title":c.siteTitle,"Content-Type":"application/json"},body:JSON.stringify({model:c.model,messages:[{role:"system",content:system},{role:"user",content:prompt}],response_format:{type:"json_object"},reasoning:{exclude:true},max_tokens:3000,temperature:.1}),signal:controller.signal,cache:"no-store"});if(!r.ok){lastError=new Error(`OPENROUTER_${r.status}`);if(r.status<500)throw lastError;continue}const raw=await r.json(),content=raw?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("OPENROUTER_INVALID_RESPONSE");return{value:schema.parse(parseModelJson(content)),model:c.model}}catch(error){lastError=error;if(!(error instanceof DOMException&&error.name==="AbortError"))throw error}finally{clearTimeout(timer)}}throw lastError instanceof Error?lastError:new Error("OPENROUTER_TIMEOUT")}
export async function gradeAssessmentAnswer(input:{kind:string;skill:string;question:string;expectedAnswer:unknown;answer:string;maxScore:number}){const out=await completeJson(Grade,"You are SCORA's strict technical examiner. Return JSON only and never exceed maxScore.",`Grade this ${input.kind} answer for ${input.skill}. Question: ${input.question}\nExpected rubric: ${JSON.stringify(input.expectedAnswer)}\nCandidate answer: ${input.answer}\nmaxScore=${input.maxScore}. Return score, concise Arabic feedback, correctness, depth, specificity, consistency, confidence.`);return{...out.value,score:Math.min(input.maxScore,out.value.score),model:out.model}}
export async function askAssistant(input:{message:string;role:string;isAdmin:boolean;context:Record<string,unknown>}){const out=await completeJson(z.object({answer:z.string().min(1).max(4000)}),"You are SSD, SCORA's Arabic assistant. Answer only from supplied live context. Never invent database facts, prices, counts, permissions, or completed actions. Return JSON only.",`Role=${input.role}; admin=${input.isAdmin}; liveContext=${JSON.stringify(input.context)}; message=${input.message}`);return{answer:out.value.answer,model:out.model}}
export async function generateInterviewTurn(input:{skills:string[];code:string;assessmentAnswers:Record<string,string>;turns:{question:string;answer:string|null}[];secondsRemaining:number}){const out=await completeJson(InterviewTurn,"You are SCORA's adaptive Arabic technical interviewer. Ask one concise question at a time based on the candidate's code and previous answers. Probe inconsistencies and practical understanding. Return JSON only.",`Skills=${JSON.stringify(input.skills)}\nCode=${input.code}\nAssessment answers=${JSON.stringify(input.assessmentAnswers)}\nPrevious interview=${JSON.stringify(input.turns)}\nSeconds remaining=${input.secondsRemaining}. Return question and shouldContinue. Continue only while another question materially improves confidence.`);return{...out.value,model:out.model}}
