import "server-only";
import { createCipheriv,createDecipheriv,createHash,randomBytes } from "node:crypto";
import { z } from "zod";
import { query,queryOne } from "@/lib/db";

const Question=z.object({kind:z.enum(["mcq","interview","code"]),skill:z.string().min(1).max(100),question:z.string().min(10),options:z.array(z.string()).min(2).max(6).optional(),expectedAnswer:z.union([z.string(),z.array(z.string())]),maxScore:z.number().int().min(1).max(100)});
const Assessment=z.object({questions:z.array(Question).min(5).max(15)});
function key(){const secret=process.env.SESSION_SECRET;if(!secret)throw new Error("SESSION_SECRET_REQUIRED");return createHash("sha256").update(secret).digest()}
export function encryptSecret(value:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv);const data=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `v1.${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${data.toString("base64url")}`}
function decryptSecret(value:string){const [,iv,tag,data]=value.split(".");const d=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));d.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([d.update(Buffer.from(data,"base64url")),d.final()]).toString("utf8")}
export async function openRouterConfig(){const rows=await query<{setting_key:string;setting_value:string}>("SELECT setting_key,setting_value FROM platform_settings WHERE setting_key IN ('openrouter_api_key','openrouter_model','openrouter_site_url','openrouter_site_title')");const m=Object.fromEntries(rows.map(x=>[x.setting_key,x.setting_value]));const stored=m.openrouter_api_key;return{apiKey:stored?decryptSecret(stored):process.env.OPENROUTER_API_KEY,model:m.openrouter_model||"openai/gpt-4.1-mini",siteUrl:m.openrouter_site_url||"http://localhost:3000",siteTitle:m.openrouter_site_title||"SCORA",hasStoredKey:Boolean(stored)}}
export async function generateAssessment(skills:string[]){const c=await openRouterConfig();if(!c.apiKey)throw new Error("OPENROUTER_NOT_CONFIGURED");const prompt=`Create a fair Arabic developer admission assessment grounded only in these claimed skills: ${skills.join(", ")}. Return JSON with questions: exactly 3 mcq, 2 interview and 1 code question. MCQ must include options. Include expectedAnswer and maxScore. Do not include markdown.`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${c.apiKey}`,"HTTP-Referer":c.siteUrl,"X-OpenRouter-Title":c.siteTitle,"Content-Type":"application/json"},body:JSON.stringify({model:c.model,messages:[{role:"system",content:"You are SCORA's technical examiner. Output valid JSON only."},{role:"user",content:prompt}],response_format:{type:"json_object"},temperature:.3}),signal:controller.signal,cache:"no-store"});if(!r.ok)throw new Error(`OPENROUTER_${r.status}`);const raw=await r.json();const content=raw?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("OPENROUTER_INVALID_RESPONSE");return{assessment:Assessment.parse(JSON.parse(content)),model:c.model,prompt,raw}}finally{clearTimeout(timer)}}
