"use server";
import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { InterviewEventType, SkillEventType } from "@scora/trust-core";
import { query,queryOne,transaction } from "@/lib/db";
import { verifySession } from "@/lib/dal";
import { appendTrustEvent } from "@/lib/trust-events";
import { generateAssessment } from "@/lib/openrouter";

export async function startDeveloperAssessment(){const s=await verifySession();if(!s||s.role!=="developer")return{ok:false as const,error:"غير مصرح"};const dev=await queryOne<{id:number;approval_status:string}>("SELECT id,approval_status FROM developers WHERE user_id=?",[s.userId]);if(!dev)return{ok:false as const,error:"ملف المطور غير موجود"};if(!s.onboardingCompleted)return{ok:false as const,error:"أكمل بياناتك أولًا"};const existing=await queryOne<{public_id:string}>("SELECT public_id FROM developer_assessment_sessions WHERE developer_id=? AND status IN ('generating','in_progress','admin_review') ORDER BY id DESC LIMIT 1",[dev.id]);if(existing)redirect(`/developer-assessment/${existing.public_id}`);const skills=(await query<{name:string}>("SELECT sk.name FROM developer_skills ds JOIN skills sk ON sk.id=ds.skill_id WHERE ds.developer_id=?",[dev.id])).map(x=>x.name);if(!skills.length)return{ok:false as const,error:"لا توجد مهارات مسجلة للاختبار"};const publicId=`assess_${randomUUID()}`;const generated=await generateAssessment(skills);await transaction(async c=>{const [r]=await c.execute("INSERT INTO developer_assessment_sessions(public_id,developer_id,status,model,prompt_json,raw_generation_json) VALUES(?,?,'in_progress',?,?,?)",[publicId,dev.id,generated.model,JSON.stringify({prompt:generated.prompt,skills}),JSON.stringify(generated.raw)]);const id=Number((r as {insertId:number}).insertId);for(const [i,q] of generated.assessment.questions.entries())await c.execute("INSERT INTO developer_assessment_questions(session_id,public_id,kind,skill,question_text,options_json,expected_answer_json,max_score,position) VALUES(?,?,?,?,?,?,?,?,?)",[id,`q_${randomUUID()}`,q.kind,q.skill,q.question,JSON.stringify(q.options??null),JSON.stringify(q.expectedAnswer),q.maxScore,i+1]);await c.execute("UPDATE developers SET approval_status='assessment_in_progress' WHERE id=?",[dev.id]);await appendTrustEvent({sessionPublicId:publicId,developerId:dev.id,assessmentPublicId:publicId,type:SkillEventType.ASSESSMENT_STARTED,source:"SERVER",payload:{assessmentId:publicId,taskCount:generated.assessment.questions.length,timeLimitMs:null}},c)});redirect(`/developer-assessment/${publicId}`)}

const Submission=z.record(z.string(),z.string().trim().min(1).max(20000));
export async function submitDeveloperAssessment(publicId:string,answers:Record<string,string>){const s=await verifySession();if(!s||s.role!=="developer")return{ok:false as const,error:"غير مصرح"};const session=await queryOne<{id:number;developer_id:number;status:string;started_at:Date}>("SELECT das.id,das.developer_id,das.status,das.started_at FROM developer_assessment_sessions das JOIN developers d ON d.id=das.developer_id WHERE das.public_id=? AND d.user_id=?",[publicId,s.userId]);if(!session||session.status!=="in_progress")return{ok:false as const,error:"الاختبار غير متاح"};const parsed=Submission.safeParse(answers);if(!parsed.success)return{ok:false as const,error:"أجب عن كل الأسئلة"};const questions=await query<{id:number;public_id:string;kind:string}>("SELECT id,public_id,kind FROM developer_assessment_questions WHERE session_id=? ORDER BY position",[session.id]);if(questions.length!==Object.keys(parsed.data).length||questions.some(q=>!parsed.data[q.public_id]))return{ok:false as const,error:"أجب عن كل الأسئلة"};await transaction(async c=>{for(const q of questions){const answer=parsed.data[q.public_id];await c.execute("INSERT INTO developer_assessment_answers(question_id,developer_id,answer_text) VALUES(?,?,?)",[q.id,session.developer_id,answer]);if(q.kind==="interview")await appendTrustEvent({sessionPublicId:publicId,developerId:session.developer_id,assessmentPublicId:publicId,type:InterviewEventType.INTERVIEW_ANSWER_RECEIVED,source:"SERVER",payload:{interviewId:publicId,questionId:q.public_id,responseMs:Math.max(0,Date.now()-new Date(session.started_at).getTime()),wordCount:answer.trim().split(/\s+/).length,transcriptRef:null,recordingRef:null}},c)}await c.execute("UPDATE developer_assessment_sessions SET status='admin_review',submitted_at=CURRENT_TIMESTAMP WHERE id=?",[session.id]);await c.execute("UPDATE developers SET approval_status='admin_review' WHERE id=?",[session.developer_id]);await appendTrustEvent({sessionPublicId:publicId,developerId:session.developer_id,assessmentPublicId:publicId,type:SkillEventType.ASSESSMENT_SUBMITTED,source:"SERVER",payload:{assessmentId:publicId,tasksCompleted:questions.length,tasksTotal:questions.length,totalDurationMs:Math.max(0,Date.now()-new Date(session.started_at).getTime())}},c)});revalidatePath("/admin");redirect("/developer-assessment/pending")}
