const fs=require('fs'),path=require('path'),mysql=require('mysql2/promise');
const env=path.join(__dirname,'..','.env.local');if(fs.existsSync(env))for(const line of fs.readFileSync(env,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);if(m&&!(m[1] in process.env))process.env[m[1]]=m[2].replace(/^["']|["']$/g,'')}
async function main(){const c=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,multipleStatements:true});
await c.query(`ALTER TABLE developers ADD COLUMN IF NOT EXISTS approval_status ENUM('profile_incomplete','assessment_in_progress','admin_review','approved','rejected') NOT NULL DEFAULT 'profile_incomplete', ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL, ADD COLUMN IF NOT EXISTS approved_by BIGINT UNSIGNED NULL, ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(1000) NULL;
CREATE TABLE IF NOT EXISTS developer_assessment_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id VARCHAR(80) NOT NULL,developer_id BIGINT UNSIGNED NOT NULL,status ENUM('generating','in_progress','admin_review','approved','rejected','generation_failed') NOT NULL DEFAULT 'generating',model VARCHAR(255) NULL,prompt_json JSON NULL,raw_generation_json JSON NULL,score INT NULL,trust_awarded INT NULL,sp_awarded INT NULL,started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,submitted_at TIMESTAMP NULL,reviewed_at TIMESTAMP NULL,reviewed_by BIGINT UNSIGNED NULL,review_reason VARCHAR(1000) NULL,UNIQUE KEY uq_assessment_public(public_id),KEY idx_assessment_developer(developer_id,status),CONSTRAINT fk_da_dev FOREIGN KEY(developer_id) REFERENCES developers(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS developer_assessment_questions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,session_id BIGINT UNSIGNED NOT NULL,public_id VARCHAR(80) NOT NULL,kind ENUM('mcq','interview','code') NOT NULL,skill VARCHAR(100) NOT NULL,question_text TEXT NOT NULL,options_json JSON NULL,expected_answer_json JSON NULL,max_score INT NOT NULL DEFAULT 10,position INT NOT NULL,UNIQUE KEY uq_daq_public(public_id),UNIQUE KEY uq_daq_position(session_id,position),CONSTRAINT fk_daq_session FOREIGN KEY(session_id) REFERENCES developer_assessment_sessions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS developer_assessment_answers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,question_id BIGINT UNSIGNED NOT NULL,developer_id BIGINT UNSIGNED NOT NULL,answer_text MEDIUMTEXT NOT NULL,score INT NULL,feedback TEXT NULL,answered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_answer_question(question_id),CONSTRAINT fk_daa_question FOREIGN KEY(question_id) REFERENCES developer_assessment_questions(id) ON DELETE CASCADE,CONSTRAINT fk_daa_dev FOREIGN KEY(developer_id) REFERENCES developers(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS trust_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id VARCHAR(100) NOT NULL,tenant_id VARCHAR(100) NOT NULL,session_public_id VARCHAR(80) NOT NULL,developer_id BIGINT UNSIGNED NOT NULL,assessment_public_id VARCHAR(80) NULL,event_type VARCHAR(100) NOT NULL,layer VARCHAR(50) NOT NULL,source VARCHAR(40) NOT NULL,producer_sequence INT NOT NULL,chain_position INT NOT NULL,occurred_at BIGINT NOT NULL,received_at BIGINT NOT NULL,payload_json JSON NOT NULL,previous_hash CHAR(64) NULL,event_hash CHAR(64) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_trust_event(event_id),UNIQUE KEY uq_trust_chain(session_public_id,chain_position),KEY idx_trust_dev(developer_id,session_public_id),CONSTRAINT fk_trust_dev FOREIGN KEY(developer_id) REFERENCES developers(id) ON DELETE CASCADE);
INSERT IGNORE INTO platform_settings(setting_key,setting_value) VALUES('openrouter_model','openai/gpt-4.1-mini'),('openrouter_site_title','SCORA');`);
await c.end();console.log('Developer admission migration complete')}
main().catch(e=>{console.error(e);process.exit(1)});
